# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  # neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j_source

  # kafka
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "user-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.xircle.common.event.UserCreationEventDto"
      enable-auto-commit: false
      isolation-level: read_committed
    listener:
      ack-mode: manual

kafka:
  broker: localhost:29092
