eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j_source

kafka:
  broker: localhost:29092
