# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3300/xircle
    username: root
    password: mysql_source
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  # kafka
  kafka:
  bootstrap-servers: localhost:29092  
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    transaction-id-prefix: "tx-"
    enable-idempotence: true  

# redis
redis:
  port: 6300
  host: localhost
  password: redis_source

# jwt
jwt:
  secret: xircle
